on: [push]
jobs:
  Profile:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
#        os: [windows-2022, windows-2019, ubuntu-22.04, ubuntu-20.04, ubuntu-18.04, macos-12, macos-11]
        os: [windows-2022, ubuntu-22.04, macos-12]
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Setup Go
        uses: actions/setup-go@v3
        with:
          go-version: ^1
      - name: Check Go version
        run: go version
      - name: Profile
        run: go run main.go profile_${{ matrix.os }}.log
      - uses: actions/upload-artifact@v3
        with:
          name: profile
          path: profile_${{ matrix.os }}.log



